config/routes.rb
Rails.application.routes.draw do
  resources :lessons do 
  	get 'delete'
  end 
  root 'lessons#edit', id: 1
  resources :comments, only: [:create, :destroy]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :lesson
  default_scope -> {order(created_at: :desc)}
  validates :lesson_id, presence: true
  validates :content, presence: true, length: {maximum: 140}
end

app/models/lesson.rb
class Lesson < ApplicationRecord
	has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@lesson = Lesson.find(params[:comment][:lesson_id])
		@comment = @lesson.comments.build(comment_params)
		if @comment.save 
			@comments = @lesson.comments.all
			flash[:success] = 'comment added'
			respond_to do |format|
				format.html { redirect_to edit_lesson_path(@lesson)}
				format.js
			end
		else
			redirect_to edit_lesson_path(@lesson)
		end
	end
	def destroy
		@comment = Comment.find(params[:id])
		@lesson = @comment.lesson
		@comments = @lesson.comments.all 
		@comment.destroy
		flash[:success] = 'comment deleted'
		respond_to do |format|
			format.html {redirect_to edit_lesson_path(@lesson)}
			format.js
		end
	end

	
	private 
	def comment_params
		params.require(:comment).permit(:content, :lesson_id)
	end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
	def index
		@lessons = Lesson.all 
	end
	def show 
		@lesson = Lesson.find(params[:id])
	end
	def new 
		@lessons = Lesson.all
		@lesson = Lesson.new 
	end
	def create
		@lessons = Lesson.all 
		@lesson = Lesson.create(lesson_params)
	end
	def edit 
		@lessons = Lesson.all 
		@lesson = Lesson.find(params[:id])
		#@comments = @lesson.comments.all
		#@comment = @lesson.comments.build
	end
	def update
		@lessons = Lesson.all
		@lesson = Lesson.find(params[:id])
		@lesson.update_attributes(lesson_params)
		
	end
	def delete 
		@lesson = Lesson.find(params[:lesson_id])
	end
	def destroy
		@lessons = Lesson.all
		@lesson = Lesson.find(params[:id])
		@lesson.destroy 
	end
	private
	def lesson_params
		params.require(:lesson).permit(:name, :instruction, :body, :note, :likes)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
class CodeRayify < Redcarpet::Render::HTML
  def block_code(code, language)
    CodeRay.scan(code, language).div
  end
end

def markdown(text)
  coderayified = CodeRayify.new(:filter_html => false, 
                                :hard_wrap => true, 
                                :prettify => true)
  options = {
    :fenced_code_blocks => true,
    :no_intra_emphasis => true,
    :autolink => true,
    :lax_html_blocks => true,
    :underline => true,
    :highlight => true,
    :footnotes => true,
    :strikethrough => true,
    :superscript => true
  }
  markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
  markdown_to_html.render(text).html_safe
end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/comments/_comment.html.erb
<% @comments.each do |comment| %>
<li class="list-group-item"> <%= comment.content %>  &nbsp;
	<%= link_to 'xóa', comment, method: :delete, remote: true, data: {confirm: 'xóa?'} %>

</li>
<% end %>

app/views/comments/create.js.erb
$('#comments').html("<%= escape_javascript(render 'comment') %>");

app/views/comments/destroy.js.erb
$('#comments').html("<%= escape_javascript(render 'comment') %>");

app/views/layouts/_footer.html.erb
<footer>
<%= link_to 'Gitlab Project', 'https://gitlab.com/ayaderaghul/course2' %> | Made with <span class="heart">&#9829;</span>
</footer>

app/views/layouts/_totop.html.erb
<button id="toTop"
    title="Go to Top" style="font-weight:bold"> lên đầu &#8593;</button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Học làm web miễn phí</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

<meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= render 'layouts/totop' %>
  </body>
</html>

app/views/lessons/_delete.html.erb
<div class="modal-dialog">
  <div class="modal-content">
  <div class="modal-header">
    <h3>Delete</h3>
  </div>
  <div class="modal-body">
  <ul class="errors"></ul>
  You sure?
  </div>
  <div class="modal-footer">
    <%= link_to "Yes", lesson_path(@lesson), method: :delete, remote: true, class: "btn btn-danger" %>
    <%= link_to "No", "#", class: "btn btn-default", data: { dismiss: "modal" } %>
  </div>
  </div>
</div>

app/views/lessons/_edit.html.erb
<textarea id="user-text" rows="20" cols="10" class='form-control'>
<%= @lesson.body %>
</textarea>

<script>


function adjustForm(f) {
	f.style.height = "1px";
	f.style.height = (f.scrollHeight + 2) + 'px';
}

$(document).ready(function(){
	let f = document.getElementById("user-text");
	adjustForm(f);
})

</script>

app/views/lessons/_form.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <%= form_for @lesson, remote: true, html: { style: "display:inline;" } do |f| %>
      <div class="modal-body">
        <ul class="errors"></ul>

        <div class="form-group">
          <%= f.label :name, class: "control-label" %>
          <%= f.text_field :name, class: "form-control textarea" %>
        </div>
        <div class="form-group">
          <%= f.label :instruction, class: "control-label" %>
          <%= f.text_area :instruction, size: '10x10', class: "form-control textarea" %>
        </div>
        <div class="form-group">
          <%= f.label :body, class: "control-label" %>
          <%= f.text_area :body, size: '10x10', class: "form-control textarea" %>
        </div>
        <div class="form-group">
          <%= f.label :note, class: "control-label" %>
          <%= f.text_area :note, size: '10x3', class: "form-control textarea" %>
        </div>
      </div>
      <div class="modal-footer">
        <%= f.submit class: "btn btn-primary" %>
        <%= link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"} %>
      </div>
    <% end %>
  </div>
</div>

app/views/lessons/_index.html.erb
<% @lessons.each do |lesson| %>
<li><%= link_to lesson.name, edit_lesson_path(lesson) %>
</li>
<% end %>

app/views/lessons/_indexfull.html.erb
<% @lessons.each do |lesson| %>

<li>
	<%= lesson.name %> |
	<%= link_to 'edit', edit_lesson_path(lesson), remote: true %> |
	<%= link_to 'delete', lesson_delete_path(lesson), remote: true %>
</li>

<% end %>

app/views/lessons/_like.html.erb
<%= form_for @lesson, remote:true do |f| %>
<%= f.hidden_field :likes, value: @lesson.likes + 1 %>
<%= f.submit %>
<% end %>

app/views/lessons/_save.js.erb
$("ul.errors").html("")
<% if @lesson.errors.any? %>
  <% @lesson.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $(".lesson-index").html("<%= escape_javascript(render 'indexfull') %>")
  $("#lesson-modal").modal("hide")
<% end %>

app/views/lessons/create.js.erb
<%= render 'save' %>

app/views/lessons/destroy.js.erb
<%= render 'save' %>

app/views/lessons/edit.html.erb
<nav>
  <%= link_to 'Mục lục', lessons_path %> >>
  <%= @lesson.name %>
  </nav>

<p class="instruction"> <%= markdown(@lesson.instruction) %> </p>
<div class="main-container">
 <div class="section-container">
 <%= render 'edit' %>
</div>
<div id="result" class="section-container result">
	<%= @lesson.body.html_safe %>
</div>
</div> 
<p class="note"><%= markdown(@lesson.note) %> </p>

<div class="pre-next">

<% l = @lessons.length %>
<% c = @lesson.id %>
<% if c >= 2 %>
	<%= link_to "< trước", edit_lesson_path(@lessons[c - 2]) %>
<% end %> 
<% if c < (l - 1) %>
    <%= link_to "tiếp >", edit_lesson_path(@lessons[c]) %>
<% end %>

 
</div>

<!--
<div id="likes-form">
 render 'shared/like_form'
</div>
<div>
 render 'shared/comment_form'
</div>
<div id="comments">
	<ul class="list-group">
 render 'comments/comment'
</ul>
</div>
-->
<script>
	$(document).ready(function(){
		$(document).on('keyup','#user-text', function(){
			localStorage.setItem("usertext", $('#user-text').val() );
			$('#result').html(localStorage.getItem('usertext'));
		})
		
	})
	
	</script>

app/views/lessons/edit.js.erb
$("#lesson-modal").html("<%= escape_javascript(render 'form') %>")
$("#lesson-modal").modal("show")

app/views/lessons/index.html.erb
<h1> Mục Lục :) </h1>

<ul>
	<%= render 'index' %>
</ul>


<h1> Cam kết chất lượng </h1>
<div class="main-container">
	<div class="section-container">
<p> Đây là kết quả ở cuối bài số 4:</p> 
<hr>

<%= image_tag('before.png') %>
</div>
<div class="section-container">
<p> Đây là kết quả ở cuối bài số 10: </p>
<hr>
<%= image_tag('after.png') %>
</div>
</div>
<hr>
<h1> Giới thiệu HTML </h1>
<p> Trong quá trình tiến hóa, sẽ có lúc ý thức nảy mầm. Rồi sẽ đến lúc ý thức đó có ngôn ngữ sau đó là chữ viết và toán học để lưu lại thông tin về thế giới. Một số loài vượn đã có chữ cái ê a và phép tính đơn giản. Sự phát minh ra máy tính, cũng là tự nhiên như hơi thở, là chiều chuyển động của lịch sử. Việc muốn ghi lại thông tin hiệu quả hơn viết lên vỏ sò là sự thôi thúc sáng tạo của loài người. Ở thời điểm này, việc bài văn bạn viết không còn đơn thuần là toàn chữ viết trên giấy A4 nữa, mà nó được đăng lên mạng, trang trí <span style="color:purple">màu mè</span>, có đầu đề <b>in đậm</b>, phần quan trọng <em>in nghiêng</em>, phần nổi bật <mark>tô màu</mark>. Ai muốn bình luận phần nào trỏ ngay vào đó để hỏi, người khác từ bên kia thế giới trả lời. HTML là công cụ giúp thể hiện sự đa chiều đó và dòng cảm xúc của một đoạn thông tin bạn muốn đăng lên mạng. Như thế nào? Ví dụ muốn thể hiện sự mạnh mẽ của chữ nào ta bọc nó trong một thẻ đánh dấu <xmp><b> </b></xmp> tức là bold (đậm, mạnh).</p>


<p>Trong sách <a href="https://aya-de-raghul.gitbook.io/phocaptinhoc/" target="_blank">Phổ cập tin học</a> có giải thích về sự tự nhiên của việc lưu lại thông tin bằng nhị phân trên máy tính. Ban đầu người ta dùng thẻ dập lỗ để hiện trạng thái bật tắt: dập lỗ là 1 và không lỗ là 0 chả hạn. Cứ thế bảng chữ cái được đánh số và quy sang nhị phân hết sau đó cho vào máy bằng thẻ dập lỗ. Bây giờ là mạch bật tắt, transistor, vết từ trên đĩa cứng, vết xước trên CD phản quang.. Bây giờ nếu bạn đưa cho trình duyệt dòng sau <xmp><h1> xin chào </h1></xmp> hắn sẽ hiểu được à bạn đang nói với hắn bằng html, hắn hiểu được h1 là thẻ đánh dấu tiêu đề to nhất và bạn bọc chữ xin chào trong đó, do đó hắn lụi cụi đi hiển thị chữ xin chào to và đậm cho bạn. Khái niệm thẻ html chỉ đơn giản như vậy thôi. </p>

<h1>Giới thiệu CSS</h1>

<p> HTML dùng các thẻ để đánh dấu văn bản của bạn, CSS sẽ theo các thẻ đó mà tô vẽ cho văn bản của bạn đẹp hơn. Bạn gọi tên thành phần đó ra (bằng thẻ, hoặc bằng tên bạn gán riêng cho hắn) sau đó viết các dòng lệnh tô màu thành phần đó. CSS sẽ được thêm vào đầu trang HTML, để các lệnh tô màu đó chảy tràn xuống dưới văn bản (vì vậy mà gọi là Cascading Stylesheet). Lệnh CSS căn bản nhìn tỉ dụ như sau: </p>


	<pre>

header {
 background-color: red;
 color: white;
 border-radius: 2%;
}
  </pre>

app/views/lessons/new.js.erb
$('#lesson-modal').html("<%= escape_javascript(render 'form') %>");
$('#lesson-modal').modal("show")

app/views/lessons/update.js.erb
<%= render 'save' %>
$('#likes-form').html("<%= escape_javascript(render 'shared/like_form') %>")
$('#likes').html("<%= @lesson.likes %>")

app/views/shared/_comment_form.html.erb
<%= form_for @comment, remote: true do |f| %>
<%= render 'shared/error_messages', object: f.object %>
<%= f.hidden_field :lesson_id, value: @lesson.id %>
<div class="form-group">
	<%= f.text_area :content, placeholder: "Sao?" %>
	<%= f.submit "Đăng", class: 'btn btn-primary' %>
</div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_like_form.html.erb
<%= form_for(@lesson, remote: true) do |f| %>

<%= f.hidden_field :likes, value: (@lesson.likes + 1) %> 
<%= button_tag(type: 'submit', id: 'heart-button') do %>
<span id="likes" ><%= @lesson.likes %></span> &#9829; 
<% end %><% end %>